apiVersion: v1
kind: Namespace
metadata:
  name: agent
  labels:
    kubernetes.io/metadata.name: agent
    agent.shell-echo.github.io/trust-zone: control-plane
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
